---
- hosts: localhost
  become: true
  tasks:
   - name: download jenkins repo apt URL for
     apt_key:
        url: 'https://pkg.jenkins.io/debian/jenkins.io.key'
        state: present
     become: yes

   - name: ensure the repository is configured
     apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present
     become: yes
   - name: update apt cache
     apt:
       update_cache: yes
       state: latest

   - name: Install java
     apt:
       name: openjdk-11-jre
       state: present

   - name: Install jenkins
     apt:
       name: jenkins
       state: latest

   - name: start jenkins
     service:
        name: jenkins
        enabled: true
        state: started



# installing docker using focal stable
---
- hosts: all
  become: yes
  tasks:
  - name: Add Docker's GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker's stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install Docker CE
    apt:
      name: docker-ce
      state: present

  - name: Install Docker Compose
    apt:
      name: docker-compose
      state: present
