---
- hosts: localhost
  become: true
  tasks:
   - name: download jenkins repo apt URL for
     apt_key:
        url: 'https://pkg.jenkins.io/debian/jenkins.io.key'
        state: present
     become: yes

   - name: ensure the repository is configured
     apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present
     become: yes
   - name: update apt cache
     apt:
       update_cache: yes
       state: latest

   - name: Install java
     apt:
       name: openjdk-11-jre
       state: present

   - name: Install jenkins
     apt:
       name: jenkins
       state: latest

   - name: start jenkins
     service:
        name: jenkins
        enabled: true
        state: started



