---
- name: Install Terraform
  hosts: all
  become: yes
  tasks:
    - name: Import Hashicorp GPG key
      shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add Hashicorp APT repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list

    - name: Update APT cache and install Terraform
      shell: apt update && apt install terraform
