---
- hosts: all
  become: true
  tasks:
  - name: Install unzip
    apt:
      name: unzip
      state: present
  - name: Download Terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
      dest: /tmp/terraform.zip
  - name: Unzip Terraform
    unarchive:
      src: /tmp/terraform.zip
      dest: /usr/local/bin/
      remote_src: yes
  - name: Set permissions
    file:
      path: /usr/local/bin/terraform
      mode: 0755
  - name: Test Terraform installation
    shell: terraform -v
